# Generated by Django 3.1 on 2020-12-30 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('quater', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cash_payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.TextField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('telephone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cloth_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cloths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('types', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Electronic_payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Geolocalisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Localisation_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MTN_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orange_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payeble_amount', models.IntegerField(null=True)),
                ('transport_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pickup_delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post_offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='image/')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.period')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing', models.BooleanField(default=False, null=True)),
                ('readytodeliver', models.BooleanField(default=False, null=True)),
                ('on_hold', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('service_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_time', models.TimeField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.client')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.type')),
            ],
        ),
        migrations.CreateModel(
            name='Price_grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloths', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.cloths')),
            ],
        ),
        migrations.CreateModel(
            name='Pressing_blanchisserie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.TextField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('telephone', models.PositiveIntegerField()),
                ('social_raison', models.TextField(max_length=30)),
                ('commend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.command')),
                ('post_offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.post_offers')),
                ('price_grid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.price_grid')),
            ],
        ),
        migrations.CreateModel(
            name='Payement_methode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_payement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.cash_payement')),
                ('electronic_payement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.electronic_payement')),
            ],
        ),
        migrations.CreateModel(
            name='Order_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('Service_provider', models.CharField(max_length=30)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.address')),
                ('cloths', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.cloths')),
                ('order_review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.order_review')),
                ('payement_methode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.payement_methode')),
                ('pickup_delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.pickup_delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payement_methode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.payement_methode')),
                ('pickup_delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.pickup_delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.address')),
                ('geolocalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.geolocalisation')),
                ('localisation_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.localisation_ip')),
            ],
        ),
        migrations.AddField(
            model_name='electronic_payement',
            name='mtn_money',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.mtn_money'),
        ),
        migrations.AddField(
            model_name='electronic_payement',
            name='orange_money',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.orange_money'),
        ),
        migrations.CreateModel(
            name='Command_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('cloth_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloths_info', to='pressing_live.order_info')),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_info', to='pressing_live.order_info')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.status')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='command_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.command_details'),
        ),
        migrations.AddField(
            model_name='command',
            name='order_service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.order_service'),
        ),
        migrations.AddField(
            model_name='command',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.status'),
        ),
        migrations.AddField(
            model_name='client',
            name='order_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.order_service'),
        ),
        migrations.AddField(
            model_name='client',
            name='pressing_blanchisserie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.pressing_blanchisserie'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='order_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_live.order_info'),
        ),
    ]
